version: "3.9"

services:
  app:
    build: .\frontend
    ports:
      - 80:5173
    volumes:
      - .\frontend\src:/app/src
  api:
    build: .\api-backend
    ports:
      - 8000:8000
    volumes:
      - .\api-backend:/var/www/html
    depends_on:
      - db
  db:
      image: mysql:8.0
      environment:
        - MYSQL_DATABASE=api_db
        - MYSQL_ALLOW_EMPTY_PASSWORD=1
      ports:
          - "3300:3306"